spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 100
  tokenHead: Bearer
  route:
    authentication:
      path: auth/login
      refresh: auth/refresh
      register: auth/register